name: 'next-ts'
services:
  nextjs:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:12345@pgsql_server:5432/kasaoka_stamp_rally
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: AIzaSyDwwuIQQcmuIe3-_vvKJCjynIQHMGYy4n0
      NEXTAUTH_SECRET: 4f8e2b9c3a1d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f
    ports:
      - '3000:3000'

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user_postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: next-ts
    ports:
      - '5432:5432'
