name: 'next-production'
services:
  server:
    build:
      context: '..'
      dockerfile: '.docker/Dockerfile-production'
    environment:
      NODE_ENV: 'production'
      NEXT_PUBLIC_URL_API: '/api'
    ports:
      - '3000:3000'
