name: 'next-production'
services:
  server:
    build:
      context: '..'
      dockerfile: '.docker/Dockerfile-production'
      args:
        NEXT_PUBLIC_URL_API: 'http://localhost:8000/api'
    ports:
      - '3000:3000'
